### ISSUE TITLE
Doobie connection check leaking

### ISSUE THREAD

**Issue by ludovicc** [kubukoz/sup#34]
Hello,

I'm using sup to monitor the health of my application, but I found a strange problem with the database connection check: it hangs, and the number of active connections in the connection pool keeps increasing. 

I can see some wait on HikariCP but cannot explain why this is happening:

```
"pool-6-thread-1" #25 prio=5 os_prio=0 cpu=4.91ms elapsed=377.32s tid=0x00007f0cec898800 nid=0x19 waiting on condition  [0x00007f0d18a79000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.1/Native Method)
	- parking to wait for  <0x00000000fa7811b8> (a java.util.concurrent.SynchronousQueue$TransferQueue)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.1/LockSupport.java:234)
	at java.util.concurrent.SynchronousQueue$TransferQueue.awaitFulfill(java.base@11.0.1/SynchronousQueue.java:761)
	at java.util.concurrent.SynchronousQueue$TransferQueue.transfer(java.base@11.0.1/SynchronousQueue.java:689)
	at java.util.concurrent.SynchronousQueue.poll(java.base@11.0.1/SynchronousQueue.java:937)
	at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:157)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:173)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at doobie.util.transactor$Transactor$fromDataSource$FromDataSourceUnapplied$$anonfun$9$$anonfun$apply$8.apply(transactor.scala:260)
	at doobie.util.transactor$Transactor$fromDataSource$FromDataSourceUnapplied$$anonfun$9$$anonfun$apply$8.apply(transactor.scala:260)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
	at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
	at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:86)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.cats$effect$internals$TrampolineEC$JVMTrampoline$$super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline$$anonfun$startLoop$1.apply$mcV$sp(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline$$anonfun$startLoop$1.apply(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline$$anonfun$startLoop$1.apply(TrampolineEC.scala:93)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:92)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:72)
	at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:52)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:136)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:351)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:372)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:312)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.1/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.1/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.1/Thread.java:834)
```

My code can be found here:

https://github.com/LREN-CHUV/woken/blob/master/src/main/scala/ch/chuv/lren/woken/dao/FeaturesRepositoryDAO.scala#L60

```
  def validate[F[_]: Effect](transactor: Transactor[F]): HealthCheck[F, Id] =
    connectionCheck(transactor)(timeoutSeconds = Some(5)).through(mods.recoverToSick)
```
```
12:22:50.784 DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=10, active=2, idle=8, waiting=0)
12:22:50.784 DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=10, active=2, idle=8, waiting=0)
12:22:50.886 DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Pool stats (total=10, active=10, idle=0, waiting=1)
12:22:50.886 DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Pool stats (total=10, active=10, idle=0, waiting=1)
12:22:50.973 DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Pool stats (total=8, active=1, idle=7, waiting=0)
12:22:50.973 DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-3 - Pool stats (total=8, active=1, idle=7, waiting=0)
12:23:01.985 INFO akka.actor.ActorSystemImpl - Request timeout encountered for request [GET /health Empty]
```

To reproduce, you can run the program in Vagrant:
https://github.com/LREN-CHUV/mip-microservices-infrastructure/blob/master/demo/algorithm-factory/woken/run.sh

Many thanks for any help, Ludovic

**Comment by kubukoz** [comment]
Hi! Thanks for submitting (and using the library!). I'll investigate this issue at some point this week.

**Comment by ludovicc** [comment]
@kubukoz Thanks. This issue does not look like directly related to sup, it's more something between doobie, HikariCP and Postgres, but you may have some idea.

**Comment by kubukoz** [comment]
I also don't think it's really anything sup-specific (because of how little code there actually is in sup to support doobie), but if there's something wrong in the way you're using it, it should be documented in sup.

I did some tests in my own app and spammed my health check (which involves checking the doobie timeout to a local postgres instance) and I never reach more than 1 active connection... but I'll keep looking (I have also yet to see how your datasource is configured)

**Comment by kubukoz** [comment]
Some things I noticed:

- You only give each transactor 2 threads for waiting for connections: `ce <- threads.fixedThreadPool[F](size = 2)`, whereas you assign a configurable amount of max connections (which is probably 10, judging by the snippets above), so *I guess* you might have deadlocks in transactional code (assuming doobie suffers from the same issues as slick, which I think is possible: https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/util/AsyncExecutor.scala#L64)
- You have a health check for each repository, even though 1 per connection pool would be just fine (I think you have around 3 transactors/CPs, and quite a bit more healthchecks than that)

I don't know how much influence the above have on the connection leak that's apparently happening, but they're probably worth investigating. Maybe you're using up all of a CP's connections in a single healthcheck (because it touches many repositories using the same pool), and the fact that there aren't enough threads causes some more issues... I'm not qualified enough to say whether that's happening, but I suggest you check these :)

P.S. left you a small PR with some refactors

**Comment by kubukoz** [comment]
Hi @ludovicc, did you figure out the root cause of this issue?

**Comment by ludovicc** [comment]
@kubukoz yes, I finally found the problem: I'm using cats IOApp, which by default uses the global Scala concurrent executor. It initialises by default with the same number of threads as cpus. 
In my environment, Docker containers are started by Mesos and constraints (cpu...) are applied to those containers. My container running the app was having less than one vCPU allocated to it and the global executor was allocating only one thread. Something seems to use up that one thread - I need to investigate what it is - but once I force the thread pool to use more threads (using -Dscala.concurrent.context.maxThreads=5), the problem is gone.
Thanks for pointing me in the right direction for that issue.
